2024-03-28T19:11:20.613+0900 INFO    [16] [281473714298912] [ssh_accessor.py:ssh_connect:91] [pro] SSH connect to: ssh-stub, port: 22
2024-03-28T19:11:20.782+0900 INFO    [16] [281473714298912] [ssh_accessor.py:ssh_connect:113] [pro] Success to make SSH connection to host: ssh-stub, port: 22, user: root, key path: /opt/ssh/id_rsa
2024-03-28T19:11:20.877+0900 INFO    [16] [281473714298912] [ssh_accessor.py:ssh_exec_command:63] [pro] Execute the command successfully. command: , exit code: 0, std_out: , std_err: 
2024-03-28T19:13:07.322+0900 INFO    [19] [281473581076512] [ssh_accessor.py:ssh_connect:91] [pro] SSH connect to: ssh-stub, port: 22
2024-03-28T19:13:07.465+0900 INFO    [19] [281473581076512] [ssh_accessor.py:ssh_connect:113] [pro] Success to make SSH connection to host: ssh-stub, port: 22, user: root, key path: /opt/ssh/id_rsa
2024-03-28T19:13:07.539+0900 INFO    [19] [281473581076512] [ssh_accessor.py:ssh_exec_command:63] [pro] Execute the command successfully. command: docker inspect vpc-gitlab -f {{json .State.Status}}", exit code: 2, std_out: , std_err: bash: -c: line 1: unexpected EOF while looking for matching `"',bash: -c: line 2: syntax error: unexpected end of file
2024-03-28T19:14:39.442+0900 INFO    [22] [281473800491040] [ssh_accessor.py:ssh_connect:91] [pro] SSH connect to: ssh-stub, port: 22
2024-03-28T19:14:39.585+0900 INFO    [22] [281473800491040] [ssh_accessor.py:ssh_connect:113] [pro] Success to make SSH connection to host: ssh-stub, port: 22, user: root, key path: /opt/ssh/id_rsa
2024-03-28T19:14:39.653+0900 INFO    [22] [281473800491040] [ssh_accessor.py:ssh_exec_command:63] [pro] Execute the command successfully. command: docker inspect vpc-gitlab -f {{json .State.Status}}, exit code: 2, std_out: , std_err: /usr/local/bin/docker: line 3: conditional binary operator expected,/usr/local/bin/docker: line 3: syntax error near `.State.Status}}"',/usr/local/bin/docker: line 3: `if [[ $1 == "inspect" && $2 == "vpc-gitlab" && $3  == "-f" && == "{{json .State.Status}}" ]]; then'
2024-03-28T19:18:01.351+0900 INFO    [32] [281472889233440] [ssh_accessor.py:ssh_connect:91] [pro] SSH connect to: ssh-stub, port: 22
2024-03-28T19:18:01.508+0900 INFO    [32] [281472889233440] [ssh_accessor.py:ssh_connect:113] [pro] Success to make SSH connection to host: ssh-stub, port: 22, user: root, key path: /opt/ssh/id_rsa
2024-03-28T19:18:01.570+0900 INFO    [32] [281472889233440] [ssh_accessor.py:ssh_exec_command:63] [pro] Execute the command successfully. command: docker inspect vpc-gitlab -f {{json .State.Status}}, exit code: 0, std_out: Invalid command, std_err: 
2024-03-28T19:19:16.069+0900 INFO    [ssh_accessor.py:ssh_connect:91] [pro] SSH connect to: ssh-stub, port: 22 [35] [281473460551712]
2024-03-28T19:19:16.211+0900 INFO    [ssh_accessor.py:ssh_connect:113] [pro] Success to make SSH connection to host: ssh-stub, port: 22, user: root, key path: /opt/ssh/id_rsa [35] [281473460551712]
2024-03-28T19:19:16.279+0900 INFO    [ssh_accessor.py:ssh_exec_command:63] [pro] Execute the command successfully. command: docker inspect vpc-gitlab -f {{json .State.Status}}, exit code: 0, std_out: Invalid command, std_err:  [35] [281473460551712]
2024-03-28T19:19:30.388+0900 INFO    [ssh_accessor.py:ssh_connect:91] [pro] SSH connect to: ssh-stub, port: 22 [38] [281473623224352]
2024-03-28T19:19:30.536+0900 INFO    [ssh_accessor.py:ssh_connect:113] [pro] Success to make SSH connection to host: ssh-stub, port: 22, user: root, key path: /opt/ssh/id_rsa [38] [281473623224352]
2024-03-28T19:19:30.599+0900 INFO    [ssh_accessor.py:ssh_exec_command:63] [pro] Execute the command successfully. command: docker inspect vpc-gitlab -f {{json .State.Status}}, exit code: 0, std_out: Invalid command, std_err:  [38] [281473623224352]
2024-03-28T19:20:02.343+0900 INFO    [41] [281473724198944] [pro] SSH connect to: ssh-stub, port: 22 [ssh_accessor.py:ssh_connect:91]
2024-03-28T19:20:02.488+0900 INFO    [41] [281473724198944] [pro] Success to make SSH connection to host: ssh-stub, port: 22, user: root, key path: /opt/ssh/id_rsa [ssh_accessor.py:ssh_connect:113]
2024-03-28T19:20:02.551+0900 INFO    [41] [281473724198944] [pro] Execute the command successfully. command: docker inspect vpc-gitlab -f {{json .State.Status}}, exit code: 0, std_out: Invalid command, std_err:  [ssh_accessor.py:ssh_exec_command:63]
2024-03-28T19:21:27.142+0900 INFO    [44] [281473645297696] [pro] SSH connect to: ssh-stub, port: 22 [ssh_accessor.py:ssh_connect:91]
2024-03-28T19:21:27.289+0900 INFO    [44] [281473645297696] [pro] Success to make SSH connection to host: ssh-stub, port: 22, user: root, key path: /opt/ssh/id_rsa [ssh_accessor.py:ssh_connect:113]
2024-03-28T19:21:27.365+0900 INFO    [44] [281473645297696] [pro] Execute the command successfully. command: docker inspect vpc-gitlab -f {{json .State.Status}}, exit code: 0, std_out: Invalid command, std_err:  [ssh_accessor.py:ssh_exec_command:63]
2024-03-28T19:22:15.994+0900 INFO    [47] [281473684836384] [pro] SSH connect to: ssh-stub, port: 22 [ssh_accessor.py:ssh_connect:91]
2024-03-28T19:22:16.143+0900 INFO    [47] [281473684836384] [pro] Success to make SSH connection to host: ssh-stub, port: 22, user: root, key path: /opt/ssh/id_rsa [ssh_accessor.py:ssh_connect:113]
2024-03-28T19:22:16.220+0900 INFO    [47] [281473684836384] [pro] Execute the command successfully. command: docker inspect vpc-gitlab -f {{json .State.Status}}}, exit code: 0, std_out: Invalid command, std_err:  [ssh_accessor.py:ssh_exec_command:63]
2024-03-28T19:23:10.992+0900 INFO    [50] [281473424478240] [pro] SSH connect to: ssh-stub, port: 22 [ssh_accessor.py:ssh_connect:91]
2024-03-28T19:23:11.142+0900 INFO    [50] [281473424478240] [pro] Success to make SSH connection to host: ssh-stub, port: 22, user: root, key path: /opt/ssh/id_rsa [ssh_accessor.py:ssh_connect:113]
2024-03-28T19:23:11.208+0900 INFO    [50] [281473424478240] [pro] Execute the command successfully. command: docker inspect vpc-gitlab -f {{json .State.Status}}, exit code: 0, std_out: Invalid command, std_err:  [ssh_accessor.py:ssh_exec_command:63]
2024-03-28T19:25:05.420+0900 INFO    [53] [281472887705632] [pro] SSH connect to: ssh-stub, port: 22 [ssh_accessor.py:ssh_connect:91]
2024-03-28T19:25:05.586+0900 INFO    [53] [281472887705632] [pro] Success to make SSH connection to host: ssh-stub, port: 22, user: root, key path: /opt/ssh/id_rsa [ssh_accessor.py:ssh_connect:113]
2024-03-28T19:25:05.657+0900 INFO    [53] [281472887705632] [pro] Execute the command successfully. command: docker inspect vpc-gitlab -f {{json .State.Status}}, exit code: 0, std_out: Invalid command, std_err:  [ssh_accessor.py:ssh_exec_command:63]
2024-03-28T19:28:45.864+0900 INFO    [59] [281472879022112] [pro] SSH connect to: ssh-stub, port: 22 [ssh_accessor.py:ssh_connect:91]
2024-03-28T19:28:46.009+0900 INFO    [59] [281472879022112] [pro] Success to make SSH connection to host: ssh-stub, port: 22, user: root, key path: /opt/ssh/id_rsa [ssh_accessor.py:ssh_connect:113]
2024-03-28T19:28:46.089+0900 INFO    [59] [281472879022112] [pro] Execute the command successfully. command: docker inspect vpc-gitlab -f "{{json .State.Status}}", exit code: 0, std_out: runninginspect,vpc-gitlab,-f,{{json .State.Status}},, std_err:  [ssh_accessor.py:ssh_exec_command:63]
2024-03-28T19:29:09.891+0900 INFO    [62] [281473744076832] [pro] SSH connect to: ssh-stub, port: 22 [ssh_accessor.py:ssh_connect:91]
2024-03-28T19:29:10.037+0900 INFO    [62] [281473744076832] [pro] Success to make SSH connection to host: ssh-stub, port: 22, user: root, key path: /opt/ssh/id_rsa [ssh_accessor.py:ssh_connect:113]
2024-03-28T19:29:10.105+0900 INFO    [62] [281473744076832] [pro] Execute the command successfully. command: docker inspect vpc-gitlab -f "{{json .State.Status}}", exit code: 0, std_out: running, std_err:  [ssh_accessor.py:ssh_exec_command:63]
2024-03-28T19:35:14.464+0900 INFO    [65] [281473232048160] [pro] SSH connect to: ssh-stub, port: 22 [ssh_accessor.py:ssh_connect:92]
2024-03-28T19:35:14.665+0900 INFO    [65] [281473232048160] [pro] Success to make SSH connection to host: ssh-stub, port: 22, user: root, key path: /opt/ssh/id_rsa [ssh_accessor.py:ssh_connect:114]
2024-03-28T19:35:14.731+0900 INFO    [65] [281473232048160] [pro] Execute the command successfully. command: docker inspect vpc-gitlab -f "{{json .State.Status}}", exit code: 0, std_out: running, std_err:  [ssh_accessor.py:ssh_exec_command:64]
2024-03-28T19:35:46.766+0900 INFO    [68] [281473023586336] [pro] SSH connect to: ssh-stub, port: 22 [ssh_accessor.py:ssh_connect:92]
2024-03-28T19:35:46.987+0900 INFO    [68] [281473023586336] [pro] Success to make SSH connection to host: ssh-stub, port: 22, user: root, key path: /opt/ssh/id_rsa [ssh_accessor.py:ssh_connect:114]
2024-03-28T19:35:47.081+0900 INFO    [68] [281473023586336] [pro] Execute the command successfully. command: docker inspect vpc-gitlab -f "{{json .State.Status}}", exit code: 0, std_out: running, std_err:  [ssh_accessor.py:ssh_exec_command:64]
2024-03-28T19:42:54.530+0900 INFO    [74] [281472945299488] [pro] SSH connect to: ssh-stub, port: 22 [ssh_accessor.py:ssh_connect:114]
2024-03-28T19:42:54.742+0900 INFO    [74] [281472945299488] [pro] Success to make SSH connection to host: ssh-stub, port: 22, user: root, key path: /opt/ssh/id_rsa [ssh_accessor.py:ssh_connect:136]
2024-03-28T19:42:54.830+0900 INFO    [74] [281472945299488] [pro] Execute the command successfully. command: docker inspect vpc-gitlab -f "{{json .State.Status}}", exit code: 0, std_out: running, std_err:  [ssh_accessor.py:ssh_exec_command:52]
2024-03-28T19:43:50.257+0900 INFO    [77] [281473123725344] [pro] SSH connect to: ssh-stub, port: 22 [ssh_accessor.py:ssh_connect:128]
2024-03-28T19:43:50.597+0900 INFO    [77] [281473123725344] [pro] Success to make SSH connection to host: ssh-stub, port: 22, user: root, key path: /opt/ssh/id_rsa [ssh_accessor.py:ssh_connect:150]
2024-03-28T19:43:50.660+0900 INFO    [77] [281473123725344] [pro] Execute the command successfully. command: docker inspect vpc-gitlab -f "{{json .State.Status}}", exit code: 0, std_out: running, std_err:  [ssh_accessor.py:ssh_exec_command:54]
2024-03-28T19:44:36.136+0900 INFO    [80] [281473290342432] [pro] SSH connect to: ssh-stub, port: 22 [ssh_accessor.py:ssh_connect:126]
2024-03-28T19:44:36.409+0900 INFO    [80] [281473290342432] [pro] Success to make SSH connection to host: ssh-stub, port: 22, user: root, key path: /opt/ssh/id_rsa [ssh_accessor.py:ssh_connect:148]
2024-03-28T19:44:36.557+0900 INFO    [80] [281473290342432] [pro] Execute the command successfully. command: docker inspect vpc-gitlab -f "{{json .State.Status}}", exit code: 0, std_out: running, std_err:  [ssh_accessor.py:ssh_exec_command:52]
2024-03-28T19:44:50.506+0900 INFO    [83] [281473354031136] [pro] SSH connect to: ssh-stub, port: 22 [ssh_accessor.py:ssh_connect:126]
2024-03-28T19:44:50.688+0900 INFO    [83] [281473354031136] [pro] Success to make SSH connection to host: ssh-stub, port: 22, user: root, key path: /opt/ssh/id_rsa [ssh_accessor.py:ssh_connect:148]
2024-03-28T19:44:50.763+0900 INFO    [83] [281473354031136] [pro] Execute the command successfully. command: docker inspect vpc-gitlab -f "{{json .State.Status}}", exit code: 0, std_out: running, std_err:  [ssh_accessor.py:ssh_exec_command:52]
2024-03-28T19:45:31.903+0900 INFO    [86] [281472927490080] [pro] SSH connect to: ssh-stub, port: 22 [ssh_accessor.py:ssh_connect:127]
2024-03-28T19:45:32.064+0900 INFO    [86] [281472927490080] [pro] Success to make SSH connection to host: ssh-stub, port: 22, user: root, key path: /opt/ssh/id_rsa [ssh_accessor.py:ssh_connect:149]
2024-03-28T19:45:43.285+0900 INFO    [89] [281473126318112] [pro] SSH connect to: ssh-stub, port: 22 [ssh_accessor.py:ssh_connect:128]
2024-03-28T19:45:43.433+0900 INFO    [89] [281473126318112] [pro] Success to make SSH connection to host: ssh-stub, port: 22, user: root, key path: /opt/ssh/id_rsa [ssh_accessor.py:ssh_connect:150]
2024-03-28T19:45:59.297+0900 INFO    [92] [281473222168608] [pro] SSH connect to: ssh-stub, port: 22 [ssh_accessor.py:ssh_connect:128]
2024-03-28T19:45:59.452+0900 INFO    [92] [281473222168608] [pro] Success to make SSH connection to host: ssh-stub, port: 22, user: root, key path: /opt/ssh/id_rsa [ssh_accessor.py:ssh_connect:150]
2024-03-28T19:46:20.165+0900 INFO    [96] [281473085448224] [pro] SSH connect to: ssh-stub, port: 22 [ssh_accessor.py:ssh_connect:128]
2024-03-28T19:46:20.318+0900 INFO    [96] [281473085448224] [pro] Success to make SSH connection to host: ssh-stub, port: 22, user: root, key path: /opt/ssh/id_rsa [ssh_accessor.py:ssh_connect:150]
2024-03-28T19:46:20.388+0900 INFO    [96] [281473085448224] [pro] Execute the command successfully. command: docker inspect vpc-gitlab -f "{{json .State.Status}}", exit code: 0, std_out: running, std_err:  [ssh_accessor.py:ssh_exec_command:54]
2024-03-28T20:07:22.815+0900 INFO    [99] [281473415729184] [pro] SSH connect to: ssh-stub, port: 22 [ssh_accessor.py:ssh_connect:135]
2024-03-28T20:07:23.010+0900 INFO    [99] [281473415729184] [pro] Success to make SSH connection to host: ssh-stub, port: 22, user: root, key path: /opt/ssh/id_rsa [ssh_accessor.py:ssh_connect:157]
2024-03-28T20:07:29.926+0900 INFO    [102] [281473298321440] [pro] SSH connect to: ssh-stub, port: 22 [ssh_accessor.py:ssh_connect:135]
2024-03-28T20:07:30.076+0900 INFO    [102] [281473298321440] [pro] Success to make SSH connection to host: ssh-stub, port: 22, user: root, key path: /opt/ssh/id_rsa [ssh_accessor.py:ssh_connect:157]
2024-03-28T20:07:30.152+0900 INFO    [102] [281473298321440] [pro] Execute the command successfully. command: docker inspect vpc-gitlab -f "{{json .State.Status}}", exit code: 0, std_out: running, std_err:  [ssh_accessor.py:ssh_exec_command:61]
2024-03-28T20:07:55.502+0900 INFO    [105] [281472997453856] [pro] SSH connect to: hoge, port: 22 [ssh_accessor.py:ssh_connect:135]
2024-03-28T20:07:55.659+0900 ERROR   [105] [281472997453856] [pro] Failed to make SSH connection to host: hoge, port: 22, user: root, key path: /opt/ssh/id_rsa [ssh_accessor.py:ssh_connect:154]
2024-03-28T20:08:47.136+0900 INFO    [14] [281473376227360] [pro] SSH connect to: ssh-stub, port: 22 [ssh_accessor.py:ssh_connect:135]
2024-03-28T20:08:47.303+0900 INFO    [14] [281473376227360] [pro] Success to make SSH connection to host: ssh-stub, port: 22, user: root, key path: /opt/ssh/id_rsa [ssh_accessor.py:ssh_connect:157]
2024-03-28T20:08:47.366+0900 INFO    [14] [281473376227360] [pro] Execute the command successfully. command: docker inspect vpc-gitlab -f "{{json .State.Status}}", exit code: 0, std_out: running, std_err:  [ssh_accessor.py:ssh_exec_command:61]
2024-03-28T20:09:50.465+0900 INFO    [17] [281473504006176] [pro] SSH connect to: ssh-stub, port: 22 [ssh_accessor.py:ssh_connect:135]
2024-03-28T20:09:50.656+0900 ERROR   [17] [281473504006176] [pro] Failed to make SSH connection to host: ssh-stub, port: 22, user: root, key path: /opt/ssh/id_rsa [ssh_accessor.py:ssh_connect:154]
2024-03-28T20:10:27.252+0900 INFO    [20] [281473176838176] [pro] SSH connect to: ssh-stub, port: 22 [ssh_accessor.py:ssh_connect:135]
2024-03-28T20:10:27.405+0900 ERROR   [20] [281473176838176] [pro] Failed to make SSH connection to host: ssh-stub, port: 22, user: root, key path: /opt/ssh/id_rsa [ssh_accessor.py:ssh_connect:154]
2024-03-28T20:10:42.655+0900 INFO    [23] [281473356591136] [pro] SSH connect to: ssh-stub, port: 22 [ssh_accessor.py:ssh_connect:135]
2024-03-28T20:10:42.795+0900 ERROR   [23] [281473356591136] [pro] Failed to make SSH connection to host: ssh-stub, port: 22, user: root, key path: /opt/ssh/id_rsa [ssh_accessor.py:ssh_connect:154]
2024-03-28T20:11:06.075+0900 INFO    [26] [281473092554784] [pro] SSH connect to: ssh-stub, port: 22 [ssh_accessor.py:ssh_connect:135]
2024-03-28T20:11:06.234+0900 ERROR   [26] [281473092554784] [pro] Failed to make SSH connection to host: ssh-stub, port: 22, user: root, key path: /opt/ssh/id_rsa [ssh_accessor.py:ssh_connect:154]
2024-03-28T20:12:24.718+0900 INFO    [31] [281473410764832] [pro] SSH connect to: ssh-stub, port: 22 [ssh_accessor.py:ssh_connect:135]
2024-03-28T20:12:24.860+0900 ERROR   [31] [281473410764832] [pro] Failed to make SSH connection to host: ssh-stub, port: 22, user: root, key path: /opt/ssh/id_rsa [ssh_accessor.py:ssh_connect:154]
2024-03-28T20:15:38.864+0900 INFO    [14] [281472975257632] [pro] SSH connect to: ssh-stub, port: 22 [ssh_accessor.py:ssh_connect:135]
2024-03-28T20:15:39.002+0900 INFO    [14] [281472975257632] [pro] Success to make SSH connection to host: ssh-stub, port: 22, user: root, key path: /opt/ssh/id_rsa [ssh_accessor.py:ssh_connect:157]
2024-03-28T20:15:39.061+0900 INFO    [14] [281472975257632] [pro] Execute the command successfully. command: docker inspect vpc-gitlab -f "{{json .State.Status}}", exit code: 0, std_out: running, std_err:  [ssh_accessor.py:ssh_exec_command:61]
2024-03-28T20:16:02.321+0900 INFO    [17] [281472981520416] [pro] SSH connect to: ssh-stub, port: 22 [ssh_accessor.py:ssh_connect:135]
2024-03-28T20:16:02.451+0900 INFO    [17] [281472981520416] [pro] Success to make SSH connection to host: ssh-stub, port: 22, user: root, key path: /opt/ssh/id_rsa [ssh_accessor.py:ssh_connect:157]
2024-03-28T20:16:02.512+0900 INFO    [17] [281472981520416] [pro] Execute the command successfully. command: docker inspect vpc-gitlab -f "{{json .State.Status}}", exit code: 0, std_out: running, std_err:  [ssh_accessor.py:ssh_exec_command:61]
2024-03-28T20:16:05.763+0900 INFO    [20] [281473187500064] [pro] SSH connect to: ssh-stub, port: 22 [ssh_accessor.py:ssh_connect:135]
2024-03-28T20:16:05.892+0900 INFO    [20] [281473187500064] [pro] Success to make SSH connection to host: ssh-stub, port: 22, user: root, key path: /opt/ssh/id_rsa [ssh_accessor.py:ssh_connect:157]
2024-03-28T20:16:05.948+0900 INFO    [20] [281473187500064] [pro] Execute the command successfully. command: docker inspect vpc-gitlab -f "{{json .State.Status}}", exit code: 0, std_out: running, std_err:  [ssh_accessor.py:ssh_exec_command:61]
2024-03-28T20:16:21.130+0900 INFO    [23] [281473518174240] [pro] SSH connect to: ssh-stub, port: 22 [ssh_accessor.py:ssh_connect:135]
2024-03-28T20:16:21.320+0900 INFO    [23] [281473518174240] [pro] Success to make SSH connection to host: ssh-stub, port: 22, user: root, key path: /opt/ssh/id_rsa [ssh_accessor.py:ssh_connect:157]
2024-03-28T20:16:21.383+0900 INFO    [23] [281473518174240] [pro] Execute the command successfully. command: docker inspect vpc-gitlab -f "{{json .State.Status}}", exit code: 0, std_out: running, std_err:  [ssh_accessor.py:ssh_exec_command:61]
2024-10-07T17:43:12.104+0900 WARNING [18] [281473518202912] [pro] Failed to send GET request. HTTPConnectionPool(host='goodlfajsdlfjogle.com', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0xffffa722ef50>: Failed to resolve 'goodlfajsdlfjogle.com' ([Errno -2] Name or service not known)")) [request.py:__get:79]
2024-10-07T17:43:22.161+0900 WARNING [18] [281473518202912] [pro] Failed to send GET request. HTTPConnectionPool(host='goodlfajsdlfjogle.com', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0xffffa7259ed0>: Failed to resolve 'goodlfajsdlfjogle.com' ([Errno -2] Name or service not known)")) [request.py:__get:79]
2024-10-07T17:43:32.205+0900 WARNING [18] [281473518202912] [pro] Failed to send GET request. HTTPConnectionPool(host='goodlfajsdlfjogle.com', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0xffffa725ba50>: Failed to resolve 'goodlfajsdlfjogle.com' ([Errno -2] Name or service not known)")) [request.py:__get:79]
2024-10-07T17:43:32.207+0900 ERROR   [18] [281473518202912] [pro] Failed to send GET request with retry. url: http://goodlfajsdlfjogle.com, params: None, headers: None, attempts: 3, wait_sec: 10, timeout: 60, kwargs: {} [request.py:get:88]
2024-10-07T17:52:23.217+0900 WARNING [14] [281472949092384] [pro] Failed to send GET request. HTTPSConnectionPool(host='hogehogeohgohe.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff85398890>: Failed to resolve 'hogehogeohgohe.com' ([Errno -2] Name or service not known)")) [request.py:__get:62]
2024-10-07T17:52:33.275+0900 WARNING [14] [281472949092384] [pro] Failed to send GET request. HTTPSConnectionPool(host='hogehogeohgohe.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff8539a290>: Failed to resolve 'hogehogeohgohe.com' ([Errno -2] Name or service not known)")) [request.py:__get:62]
2024-10-07T17:52:43.336+0900 WARNING [14] [281472949092384] [pro] Failed to send GET request. HTTPSConnectionPool(host='hogehogeohgohe.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0xffff8539bc50>: Failed to resolve 'hogehogeohgohe.com' ([Errno -2] Name or service not known)")) [request.py:__get:62]
2024-10-07T17:52:43.347+0900 ERROR   [14] [281472949092384] [pro] Failed to send GET request with retry. url: https://hogehogeohgohe.com, params: None, headers: None, attempts: 3, wait_sec: 10, timeout: 60, kwargs: {} [request.py:get:71]
